Add better error to objax.GradValues function for input_argnums
google/objax pull request #144
Opened 2020-11-17 20:22 UTC by carlini

Currently `input_argnums` expects a tuple. If you pass the integer 0, then the `or` treats this as if you passed nothing, and so  it passes an empty tuple and silently does the wrong thing. This fixes that to check the type.

2020-11-18 05:40 UTC, david-berthelot requested changes

2020-11-18 05:40 UTC, david-berthelot commented on objax/gradient.py
> +            self.input_argnums = input_argnums
I don't think we need an if statement, we can keep the code simple by changing the assert condition.
```suggestion
        assert isinstance(input_argnums, tuple) or input_argnums is None, \
                f'Must pass a tuple of indices to input_argnums; received {input_argnums}.'
        self.input_argnums = input_argnums or tuple()
```

Also nit, let's use single quotes to keep string consistency with rest of code.

2020-11-18 06:28 UTC, david-berthelot requested changes

2020-11-18 06:28 UTC, david-berthelot commented on objax/gradient.py
> +                f'Must pass a tuple of indices to input_argnums; received {input_argnums}.'
There's a flake8 error. Can you fix it?

2020-11-21 06:59 UTC, carlini commented
Pushing fix

2020-11-21 07:06 UTC, david-berthelot requested changes

2020-11-21 07:06 UTC, david-berthelot commented on objax/io/checkpoint.py
> +            f"Must pass a VarCollection to save; received type {type(vc)}."
Nit: coding style consistency, also I believe you meant restore not save here.
```suggestion
            f'Must pass a VarCollection to restore; received type {type(vc)}.'
```

2020-11-21 07:07 UTC, david-berthelot requested changes

2020-11-21 07:07 UTC, david-berthelot commented on objax/io/checkpoint.py
> +            f"Must pass a VarCollection to save; received type {type(vc)}."
```suggestion
            f'Must pass a VarCollection to save; received type {type(vc)}.'
```

2020-11-21 07:12 UTC, david-berthelot approved these changes

2020-11-21 07:18 UTC, merged