[Proposal] Orthogonal Initializer
google/objax pull request #83
Opened 2020-10-01 11:46 UTC by joaogui1

This PR implements the [orthogonal intialization](https://smerity.com/articles/2016/orthogonal_init.html), useful for training RNNs (and maybe general Neural Nets when combined with Orthogonal regularization)
Is there interest in this PR?

2020-10-01 17:50 UTC, david-berthelot commented
Definitely welcome, is it ready for review or is it in progress?
About the orthogonalization axis, what is its typical value (fanin, output, something else)?

2020-10-07 12:49 UTC, joaogui1 commented
My bad, the orthogonalization axis is generally the last one. The PR is ready to be reviewed @david-berthelot

2020-10-07 15:50 UTC, david-berthelot requested changes
Can you also add some unit tests in `tests/`, there are already some examples to get inspired from.

2020-10-07 15:50 UTC, david-berthelot commented on objax/nn/init.py
> +    return gain * q_mat
Let's return a JAX array.
```suggestion
    return gain * jn.array(q_mat)
```

2020-10-07 15:50 UTC, david-berthelot commented on objax/nn/init.py
> +    return random.truncated_normal(shape, stddev=stddev, lower=lower, upper=upper)
I think you accidentally removed a newline character at the end.

2020-10-09 18:47 UTC, david-berthelot requested changes

2020-10-09 18:47 UTC, david-berthelot commented on tests/nn_init.py
> +                diff = I_ - np.eye(np.min(s))
Can we use non-uppercase letters (they're typically for global constants)?

2020-10-09 21:08 UTC, david-berthelot approved these changes
Thanks!

2020-10-09 21:08 UTC, merged